version: '3.7'
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - axon

  axonserver:
    image: axoniq/axonserver:4.1.1
    container_name: axonserver
    hostname: axonserver
    ports:
      - "8024:8024"
      - "8124:8124"
      - "8224:8224"
    environment:
      - AXONSERVER_HOSTNAME=axonserver
    networks:
      - axon

  h2db:
    container_name: h2db
    build:
      context: ./axon-multi-db
    ports:
      - "8079:8079"
      - "9090:9090"
  #    volumes:
  #      - ./axon-multi-db/target/axon-multi-db-1.0-SNAPSHOT.jar:/app.jar
    networks:
      - axon

  person:
    container_name: person
    build:
      context: ./axon-multi-person
    ports:
      - "8080:8080"
    environment:
      - AXON_SERVER=axonserver
      - H2_DB_HOST=h2db
      - RABBITMQ_HOST=rabbitmq
    command: >
      dockerize
      -wait tcp://axonserver:8124 -timeout 60s
      -wait tcp://h2db:9090 -timeout 60s
      java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
  #    volumes:
  #      - ./axon-multi-person/target/axon-multi-person-1.0-SNAPSHOT.jar:/app.jar
    networks:
      - axon

  address:
    container_name: address
    build:
      context: ./axon-multi-address
    ports:
      - "8081:8081"
    environment:
      - AXON_SERVER=axonserver
      - H2_DB_HOST=h2db
      - RABBITMQ_HOST=rabbitmq
    command: >
      dockerize
      -wait tcp://axonserver:8124 -timeout 60s
      -wait tcp://h2db:9090 -timeout 60s
      java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
  #    volumes:
  #      - ./axon-multi-address/target/axon-multi-address-1.0-SNAPSHOT.jar:/app.jar
    networks:
      - axon

  saga:
    container_name: saga
    build:
      context: ./axon-multi-saga
    ports:
      - "8082:8082"
    environment:
      - AXON_SERVER=axonserver
      - H2_DB_HOST=h2db
      - RABBITMQ_HOST=rabbitmq
    command: >
      dockerize
      -wait tcp://axonserver:8124 -timeout 60s
      -wait tcp://h2db:9090 -timeout 60s
      java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
#    volumes:
#      - ./axon-multi-saga/target/axon-multi-saga-1.0-SNAPSHOT.jar:/app.jar
    networks:
      - axon

  projection:
    container_name: projection
    build:
      context: ./axon-multi-projection
    ports:
      - "8083:8083"
    environment:
      - AXON_SERVER=axonserver
      - H2_DB_HOST=h2db
      - RABBITMQ_HOST=rabbitmq
    command: >
      dockerize
      -wait tcp://axonserver:8124 -timeout 60s
      -wait tcp://h2db:9090 -timeout 60s
      java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
#    volumes:
#      - ./axon-multi-projection/target/axon-multi-projection-1.0-SNAPSHOT.jar:/app.jar
    networks:
      - axon

networks:
  axon:
    driver: bridge